skills = [('Unix', 1),
('Linux', 1),
('MacOS', 1),
('Windows', 1),
('Security', 3),
('Office products', 1),
('Databases', 6),
('IDEs', 1),
('Communication', 1),
('Environment setup', 1),
('Ansible', 2),
('Presentation', 1),
('Java', 3),
('PHP', 0),
('JavaScript', 0),
('Go', 3),
('C#', 3),
('Python', 3),
('C', 0),
('C++', 0),
('Frameworks', 4),
('Bro-Skills', 7)]